version: '3.7'

services:
  docs:
    image: '${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}'
    networks:
      - cluster
    volumes:
      - '${NGINX_CONF}:/etc/nginx/nginx.conf'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    logging:
      driver: loki
      options:
        loki-url: '${LOKI_URL}'
        loki-external-labels: 'job=logs,logs_provider=nginx,traefik_service=${TRAEFIK_NAME}@docker'
        loki-pipeline-stage-file: '${LOKI_PIPELINE_STAGE_FILE}'
    deploy:
      mode: global
      placement:
        constraints:
          - 'node.hostname == ${DOCKER_STACK_NODE_HOSTNAME}'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        # Traefik (General)
        - 'traefik.enable=true'
        # Traefik (Services)
        - 'traefik.http.services.${TRAEFIK_NAME}.loadbalancer.server.port=80'
        # Traefik (Middlewares)
        - 'traefik.http.middlewares.${TRAEFIK_NAME}-stripprefix.stripprefix.prefixes=${TRAEFIK_PATH_PREFIX}'
        # Traefik (Routers - HTTP)
        - 'traefik.http.routers.${TRAEFIK_NAME}-http.entrypoints=web'
        - 'traefik.http.routers.${TRAEFIK_NAME}-http.middlewares=http-to-https,real-ip'
        - 'traefik.http.routers.${TRAEFIK_NAME}-http.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`${TRAEFIK_PATH_PREFIX}`)'
        - 'traefik.http.routers.${TRAEFIK_NAME}-http.service=${TRAEFIK_NAME}'
        # Traefik (Routers - HTTPS)
        - 'traefik.http.routers.${TRAEFIK_NAME}-https.entrypoints=websecure'
        - 'traefik.http.routers.${TRAEFIK_NAME}-https.middlewares=real-ip,${TRAEFIK_NAME}-stripprefix'
        - 'traefik.http.routers.${TRAEFIK_NAME}-https.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`${TRAEFIK_PATH_PREFIX}`)'
        - 'traefik.http.routers.${TRAEFIK_NAME}-https.service=${TRAEFIK_NAME}'

networks:
  cluster:
    external: true
